<?php 

CREATE TABLE CLIENTE (
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(255) NOT NULL, 
    TELEFONE VARCHAR(50) NOT NULL, 
    ENDERECO VARCHAR(255) NOT NULL, 
    CEP VARCHAR(8) NOT NULL, 
    PRIMARY KEY (CPF),
    FOREIGN KEY (ID_EMPRESTIMO) REFERENCES EMPRESTIMO(ID_EMPRESTIMO)
); 

CREATE TABLE EMPRESTIMO (
    ID_EMPRESTIMO INT NOT NULL AUTO_INCREMENT, 
    NUMERO INT NOT NULL, 
    VALOR DECIMAL(10,2) NOT NULL, 
    PRIMARY KEY (ID_EMPRESTIMO),
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
); 




?> 